# Generated by Django 2.0.12 on 2020-04-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='գրանցում',
            name='ԳրանցմանԱմսաթիվ',
        ),
    ]
