# Generated by Django 2.0.12 on 2020-04-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0002_remove_գրանցում_գրանցմանամսաթիվ'),
    ]

    operations = [
        migrations.AddField(
            model_name='գրանցում',
            name='ԳրանցմանԱմսաթիվ',
            field=models.DateField(blank=True, null=True, verbose_name='Գրանցման ամսաթիվ'),
        ),
    ]
