# Generated by Django 2.0.12 on 2020-04-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anamnez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='անամնեզ',
            name='հհ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում'),
        ),
    ]
