# Generated by Django 2.0.12 on 2020-03-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YndhanurTexekutyunner', '0002_auto_20200303_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='հհ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում'),
        ),
    ]
