# Generated by Django 2.0.12 on 2020-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YndhanurTexekutyunner', '0003_auto_20200303_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='ԾառայավայրիՀասցեն',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Ծառայավայրի հասցեն'),
        ),
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='ԾառայավայրիՀեռախոսահամարը',
            field=models.IntegerField(blank=True, help_text='+***********', null=True, verbose_name='Ծառայավայրի հեռախոսահամարը'),
        ),
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='ՏանՀեռախոսահամարը',
            field=models.IntegerField(blank=True, help_text='+***********', null=True, verbose_name='Տան հեռախոսահամարը'),
        ),
    ]
